### ISSUE TITLE
withClerkHandler() returns an object that cannot be serialized

### ISSUE THREAD

**Issue by t-eckert** [wobsoriano/svelte-clerk#36]
First of all, thank you for building this library! It got me up and running with Clerk within 30 minutes in my Sveltekit app. 

It looks like this project is still under development and you are likely aware of this problem, but I wanted to submit an issue just in case.

[`withClerkHandler`](https://github.com/wobsoriano/svelte-clerk/blob/main/src/lib/server/withClerkHandler.ts) adds the `authObject` to `locals` as `auth`. This object has three functions on it `getToken`, `has`, and `debug` which are not serializable. 

This means that the resolved event cannot be passed to the client. Otherwise you get the error:

<details><summary>Details</summary>
<pre><code>
  Error: Data returned from `load` while rendering /(pages)/(home)/feeds/popular is not serializable: Cannot stringify a function (data.auth.getToken)
    at get_data (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:592:9)
    at Module.render_response (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:264:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.render_page (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:286:10)
    at async resolve (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:446:18)
    at async Module.respond (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:20)
    at async file:///Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22
Error: Data returned from `load` while rendering /(pages)/(home)/feeds/popular is not serializable: Cannot stringify a function (data.auth.getToken)
    at get_data (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:592:9)
    at Module.render_response (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:264:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.respond_with_error (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:85:10)
    at async Module.render_page (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:305:10)
    at async resolve (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:446:18)
    at async Module.respond (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:20)
    at async file:///Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22
Error: Data returned from `load` while rendering /(pages)/[blog] is not serializable: Cannot stringify a function (data.auth.getToken)
    at get_data (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:592:9)
    at Module.render_response (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:264:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.render_page (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:234:15)
    at async resolve (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:446:18)
    at async Module.respond (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:20)
    at async file:///Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22
Error: Data returned from `load` while rendering /(pages)/[blog] is not serializable: Cannot stringify a function (data.auth.getToken)
    at get_data (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:592:9)
    at Module.render_response (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:264:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.respond_with_error (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:85:10)
    at async Module.render_page (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:305:10)
    at async resolve (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:446:18)
    at async Module.respond (/Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:20)
    at async file:///Users/thomaseckert/Repos/github.com/t-eckert/devy/frontend/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22
</code></pre>
</details> 

At least when using the hook as in the README:

```ts
import { withClerkHandler } from 'svelte-clerk/server';

export const handle = withClerkHandler();
```

I bet you already know this because in the [`hooks.server.ts`](https://github.com/wobsoriano/svelte-clerk/blob/main/src/hooks.server.ts) file you use the `Security` class to elide this problem.

The issue I have is that the `Security` class is not available (AFAICT) to consumers of the library.

Right now, I'm able to get around this with the following code in my `hooks.server.ts`:

```ts
import type { Handle } from "@sveltejs/kit"
import { sequence } from "@sveltejs/kit/hooks";
import { withClerkHandler } from "svelte-clerk/server"

export const handle: Handle = sequence(
  withClerkHandler(),
  ({ event, resolve }) => {

    // Forgive me JS gods.
    // @ts-expect-error to bypass serializability issues
    delete event.locals.auth.getToken
    // @ts-expect-error to bypass serializability issues
    delete event.locals.auth.has
    // @ts-expect-error to bypass serializability issues
    delete event.locals.auth.debug

    return resolve(event);
  }
);
```

But I would love if the `Security` class could be made available so I could use it. Or if you have other designs, that the `withClerkHandler` function be modified to return a serializable object.

Please let me know if there is a way around this problem that I'm not aware of. If you have a write-up of how you'd want to fix `withClerkHandler` to be serializable, I'd be happy to fork and knock it out.

**Comment by wobsoriano** [comment]
Hey, thanks for trying this package out!

> [withClerkHandler](https://github.com/wobsoriano/svelte-clerk/blob/main/src/lib/server/withClerkHandler.ts) adds the authObject to locals as auth. This object has three functions on it getToken, has, and debug which are not serializable.

Are you passing the `locals.auth` object to client? I suggest to pick **only the fields you need**. If you really need to pass the `locals.auth` for some reason, you can use this internal function from `@clerk/backend` (would love to know your use case):

```ts
import { makeAuthObjectSerializable } from '@clerk/backend/internal';

export const load = async ({ locals }) => {
   return {
	auth: makeAuthObjectSerializable(locals.auth)
   };
};
```

We need the `has` and other functions from `locals.auth` when guarding pages for example:

```ts
import { redirect } from '@sveltejs/kit'

export const load = async ({ locals }) => {
  if (!locals.auth.has({ permission: 'org:invoices:create' })) {
    return redirect(307, '/sign-in')
  }
  
  return {};
};
```

> But I would love if the Security class could be made available so I could use it. Or if you have other designs, that the withClerkHandler function be modified to return a serializable object.

Unfortunately, this should be in user-land. This `Security` class is inspired from [this great blog post](https://www.captaincodeman.com/securing-your-sveltekit-app).

**Comment by wobsoriano** [comment]
Closing this one but feel free to ask more questions!
